vertx:
  maxEventLoopExecuteTime: 7000
  maxWorkerExecuteTime: 30000
  server:
    port: 12345
    rootPath: pers.vincent.vertxboot

spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/test0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere:
    props:
      sql:
        #设置sql是否展示
        show: true
    datasource:
      #数据库名称（可以与数据库中的库名不一致）
      names: test0,test1
      test0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        # 数据库连接池的最小连接数
        min-idle: 5
        # 初始化连接数
        initial-size: 5
        # 最大连接数
        max-total: 5
        max-wait-millis: 200s
      test1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        # 数据库连接池的最小连接数
        min-idle: 5
        # 初始化连接数
        initial-size: 5
        # 最大连接数
        max-total: 5
        max-wait-millis: 200s
    sharding:
      #分库策略
      default-database-strategy:
        inline:
          #根据id取模决定去那个库
          algorithm-expression: test$->{id % 2}
          sharding-column: id
      tables:
        #逻辑表名，这里的user_info为逻辑表名，user_info_0,user_info_1为实际表
        user_info:
          actual-data-nodes: test$->{0..1}.user_info_$->{0..1}
          table-strategy:
            #根据id取模决定去那个表
            inline:
              sharding-column: id
              algorithm-expression: user_info_$->{id % 2}
          key-generator:
            #id使用雪花算法
            column: id
            #雪花算法
            type: SNOWFLAKE
